
import java.awt.Color;
import java.awt.Graphics;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class TelaEdicao extends javax.swing.JFrame {

    private Fase fase;
    private Objeto novoObjeto = null;
    private Objeto objetoMovido = null;
    private Objeto abaixoDoMouse = null;
    public TelaEdicao(Fase fase) {
        this.fase = fase;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NovoCarroPalhacao = new javax.swing.JButton();
        LabelMenuLateral = new javax.swing.JLabel();
        NovoCanhao = new javax.swing.JButton();
        NovaCartola = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        NovaCartola1 = new javax.swing.JButton();
        NovaCartola2 = new javax.swing.JButton();
        NovaCartola3 = new javax.swing.JButton();
        NovaCartola4 = new javax.swing.JButton();
        NovaCartola5 = new javax.swing.JButton();
        NovaCartola6 = new javax.swing.JButton();
        NovaCartola8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Fase = new javax.swing.JMenu();
        Abria = new javax.swing.JMenuItem();
        Exporta = new javax.swing.JMenuItem();
        Ajuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        NovoCarroPalhacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Pendulo.png"))); // NOI18N

        LabelMenuLateral.setText("Novo:");

        NovoCanhao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Canhao.png"))); // NOI18N
        NovoCanhao.setText("Canhao");
        NovoCanhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoCanhaoActionPerformed(evt);
            }
        });

        NovaCartola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cartola_Azul.png"))); // NOI18N
        NovaCartola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaCartolaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MoveObjeto(evt);
                MarcaObjeto(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SoltaObjeto(evt);
                SelecionaObjeto(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        NovaCartola1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cartola_Azul.png"))); // NOI18N
        NovaCartola1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaCartola1ActionPerformed(evt);
            }
        });

        NovaCartola2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cartola_Amarela.png"))); // NOI18N
        NovaCartola2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaCartola2ActionPerformed(evt);
            }
        });

        NovaCartola3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cartola_Amarela.png"))); // NOI18N
        NovaCartola3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaCartola3ActionPerformed(evt);
            }
        });

        NovaCartola4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cartola_Vermelha.png"))); // NOI18N
        NovaCartola4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaCartola4ActionPerformed(evt);
            }
        });

        NovaCartola5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cartola_Vermelha.png"))); // NOI18N
        NovaCartola5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaCartola5ActionPerformed(evt);
            }
        });

        NovaCartola6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cartola_Verde.png"))); // NOI18N
        NovaCartola6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaCartola6ActionPerformed(evt);
            }
        });

        NovaCartola8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cartola_Verde.png"))); // NOI18N
        NovaCartola8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaCartola8ActionPerformed(evt);
            }
        });

        Fase.setText("Fase");

        Abria.setText("Abrir");
        Fase.add(Abria);

        Exporta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, 0));
        Exporta.setText("Exportar");
        Exporta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportaActionPerformed(evt);
            }
        });
        Fase.add(Exporta);

        jMenuBar1.add(Fase);

        Ajuda.setText("Ajuda");
        jMenuBar1.add(Ajuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NovoCanhao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NovoCarroPalhacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelMenuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(NovaCartola1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NovaCartola, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(NovaCartola3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(NovaCartola2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(NovaCartola4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(NovaCartola5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NovaCartola8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NovaCartola6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelMenuLateral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NovoCarroPalhacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NovoCanhao, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NovaCartola)
                            .addComponent(NovaCartola1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NovaCartola6)
                            .addComponent(NovaCartola8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NovaCartola2)
                            .addComponent(NovaCartola3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NovaCartola5)
                            .addComponent(NovaCartola4))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExportaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExportaActionPerformed

    private void NovoCanhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoCanhaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NovoCanhaoActionPerformed

    private void MoveObjeto(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoveObjeto
        Graphics g = jPanel1.getGraphics();
        g.setColor(Color.white);
        g.fillRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
            
        for(Objeto atuador: fase.getAtuadores()){
            atuador.desenha(g);
        }
        
        if(novoObjeto != null){
            novoObjeto.setX(evt.getX());
            novoObjeto.setY(evt.getY());
            novoObjeto.desenha(g);
            g.setColor(Color.RED);
            g.drawRect(novoObjeto.getX(), novoObjeto.getY(), novoObjeto.getLargura(), novoObjeto.getAltura());
        }
        if(objetoMovido != null){
            objetoMovido.setX(evt.getX());
            objetoMovido.setY(evt.getY());
            objetoMovido.desenha(g);
            g.setColor(Color.RED);
            g.drawRect(objetoMovido.getX(), objetoMovido.getY(), objetoMovido.getLargura(), objetoMovido.getAltura());
        }
        
    }//GEN-LAST:event_MoveObjeto

    private void NovaCartolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaCartolaActionPerformed
            novoObjeto = new Cartola(100, 100);
    }//GEN-LAST:event_NovaCartolaActionPerformed

    private void SoltaObjeto(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SoltaObjeto
        if(novoObjeto != null){
            fase.adicionaObjeto(novoObjeto);
            System.out.println("adicionou objeto");
        }
        objetoMovido = null;
        novoObjeto = null;
    }//GEN-LAST:event_SoltaObjeto

    private void SelecionaObjeto(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelecionaObjeto
        if(abaixoDoMouse != null && novoObjeto == null){
            objetoMovido = abaixoDoMouse;
            System.out.println("chou novo abaixo do mouse");
        }
    }//GEN-LAST:event_SelecionaObjeto

    private void MarcaObjeto(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarcaObjeto
        Objeto aux = null;
        for(Objeto atuador: fase.getAtuadores()){
                if(atuador.colisao(evt.getX(), evt.getY())){
                    aux = atuador;
                    System.out.println("objeto abaixo do mouse");
                }
        }
        abaixoDoMouse=aux;
    }//GEN-LAST:event_MarcaObjeto

    private void NovaCartola1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaCartola1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NovaCartola1ActionPerformed

    private void NovaCartola2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaCartola2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NovaCartola2ActionPerformed

    private void NovaCartola3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaCartola3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NovaCartola3ActionPerformed

    private void NovaCartola4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaCartola4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NovaCartola4ActionPerformed

    private void NovaCartola5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaCartola5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NovaCartola5ActionPerformed

    private void NovaCartola6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaCartola6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NovaCartola6ActionPerformed

    private void NovaCartola8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaCartola8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NovaCartola8ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abria;
    private javax.swing.JMenu Ajuda;
    private javax.swing.JMenuItem Exporta;
    private javax.swing.JMenu Fase;
    private javax.swing.JLabel LabelMenuLateral;
    private javax.swing.JButton NovaCartola;
    private javax.swing.JButton NovaCartola1;
    private javax.swing.JButton NovaCartola2;
    private javax.swing.JButton NovaCartola3;
    private javax.swing.JButton NovaCartola4;
    private javax.swing.JButton NovaCartola5;
    private javax.swing.JButton NovaCartola6;
    private javax.swing.JButton NovaCartola8;
    private javax.swing.JButton NovoCanhao;
    private javax.swing.JButton NovoCarroPalhacao;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
